const path=require("path")
const filePath=path.join(__dirname,"sample.txt")
console.log(filePath)
const absolutePath=path.resolve("path","sample.txt")
console.log(absolutePath)
console.log(path.dirname(filePath))
console.log(path.basename(filePath))
console.log(path.extname(filePath))
console.log(path.basename(filePath,'.txt'))
console.log(path.normalize("c:\\Users\\aravi\\OneDrive\\Desktop\\Node Training\\path\\sample.txt"))
console.log(path.isAbsolute("path\sample.txt"))
//parsing the Filepath
console.log(path.parse(filePath).root)
console.log(path.parse(filePath).dir)
console.log(path.parse(filePath).base)
console.log(path.parse(filePath).ext)