let actors=["Nani","Ranbir","Vijay","Prabhas","MaheshBabu","Ram","NTR",]
console.log(`Array Before any Operation:`)
console.log(actors)
actors.push("Nagarjuna","PawanKalyan")
console.log("Array After Pushing 2 Actors:")
console.log(actors)
actors.pop()
console.log("Array After Pop:")
console.log(actors)
console.log("Array After String Operation:")
console.log(actors.toString())
actors.unshift("Nithin","Arjun")
console.log("Array After adding element to Begining:")
console.log(actors)
actors.shift()
console.log("Array After Deleting element to Begining:")
console.log(actors)
console.log("Array After slice operation:")
console.log(actors.slice(1,5))
console.log("Array After splice operation:")
actors.splice(6,2,"Varun","Vicky")
console.log(actors)
let cars=["fortuner","Swift","Lamborigini"]
console.log("After conactination with cars Array")
console.log(actors.concat(cars))
